name: Fix postBuild permissions
on: [push]

jobs:
  fix-permissions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Make postBuild executable
        run: chmod +x postBuild
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add postBuild
          git commit -m "Make postBuild executable via GitHub Actions"
          git push
